/**
 * @fileoverview AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is generated by: bun run generate:errors
 * Source: script/generate-error-signatures.ts
 *
 * Generated: 2026-01-23T13:43:09.761Z
 * Total errors: 118
 *
 * When contracts are updated, re-run the generator to update this file.
 * TypeScript will then show errors if error-ux-mappings.ts is missing entries.
 */

// ============================================================================
// Error Signature Union Type
// ============================================================================

/**
 * Union type of all known error signatures from Floor Markets contracts.
 * This ensures type safety when mapping errors to UX messages.
 */
export type KnownErrorSignature =
  | '0x6697b232'
  | '0xe2517d3f'
  | '0x0f2a11ba'
  | '0x4ca249dc'
  | '0xc86af699'
  | '0xe04b1819'
  | '0xc9052a7a'
  | '0x8765fe9e'
  | '0x78878655'
  | '0xe80a3381'
  | '0x17cfecb6'
  | '0x1e674ad4'
  | '0xbca02987'
  | '0xe4369ad8'
  | '0x53888fca'
  | '0xa1f6025c'
  | '0x1f52d7ae'
  | '0x37f615e7'
  | '0x73937fff'
  | '0x406480c1'
  | '0x3c5094de'
  | '0x9e79f854'
  | '0xfb8f41b2'
  | '0xe450d38c'
  | '0xe602df05'
  | '0x392e1e27'
  | '0xec442f05'
  | '0x96c6fd1e'
  | '0x94280d62'
  | '0x94eef58a'
  | '0xc845a056'
  | '0x70647f79'
  | '0xd2650cd1'
  | '0xd6bda275'
  | '0xb06ebf3d'
  | '0xa4e0eec9'
  | '0x2e23a773'
  | '0x8333c4a6'
  | '0xcf479181'
  | '0x752d88c0'
  | '0xf92ee8a9'
  | '0xa972f3d2'
  | '0x7c519051'
  | '0xbe27c5b7'
  | '0x7e5cf732'
  | '0x5b784de5'
  | '0x7a625bbe'
  | '0xe1242708'
  | '0x1bb5195f'
  | '0x7ea9d542'
  | '0xb5d3d39c'
  | '0x9860564d'
  | '0xb8d4508f'
  | '0xe5b90295'
  | '0x5a123629'
  | '0xae6544c7'
  | '0xa4716b72'
  | '0x882a2be3'
  | '0xecbc7909'
  | '0xe8e3a91b'
  | '0x3f3c72cc'
  | '0x85591c03'
  | '0xb1e5d973'
  | '0x26831539'
  | '0xff17a9c5'
  | '0x308e1d3b'
  | '0x0db6a82c'
  | '0xf3d0ae0e'
  | '0xea969350'
  | '0x54fe6890'
  | '0xd08bdb84'
  | '0x62bcaf22'
  | '0x23c42ef0'
  | '0x51cfef5f'
  | '0xde504dfe'
  | '0xea7ec715'
  | '0x85a2648b'
  | '0x21af7e45'
  | '0x99bb7d2d'
  | '0x5489340e'
  | '0x94ba0164'
  | '0x0a1cfefe'
  | '0x484caa15'
  | '0x9d4878c9'
  | '0x9a71ec39'
  | '0x00f94c58'
  | '0x14ecb929'
  | '0xe1ddeaf8'
  | '0x7ba48bfd'
  | '0x2c893c25'
  | '0xf4b9de6c'
  | '0xae34fee4'
  | '0xba7b44d6'
  | '0x5f60529f'
  | '0xb8ac5f88'
  | '0xf9596d32'
  | '0xadc1baa1'
  | '0x9bc9dc56'
  | '0x79b3d744'
  | '0xbc885f3d'
  | '0xd7e6bcf8'
  | '0x1e4fbdf7'
  | '0x118cdaa7'
  | '0x842b8bd1'
  | '0xdb351373'
  | '0xd6ec36a7'
  | '0x5cd7b824'
  | '0x29168c21'
  | '0xfab2a8f9'
  | '0xbd5fc4da'
  | '0x189bb1f2'
  | '0x8c66b6e0'
  | '0x654a5dde'
  | '0x63a69154'
  | '0xc19cf6bb'
  | '0x62df6dff'
  | '0x3ee5aeb5'
  | '0x5274afe7'

// ============================================================================
// Error Metadata
// ============================================================================

/**
 * Metadata for each error extracted from ABIs.
 */
export type ErrorMetadata = {
  /** The Solidity error name */
  name: string
  /** Error input parameters */
  inputs: Array<{ name: string; type: string }>
  /** Source contract(s) that define this error */
  source: string
}

/**
 * Mapping of error signatures to their metadata.
 * Used for error decoding and display.
 */
export const ERROR_METADATA: Record<KnownErrorSignature, ErrorMetadata> = {
  '0x6697b232': {
    name: 'AccessControlBadConfirmation',
    inputs: [],
    source: 'AUT_Roles_v2',
  },
  '0xe2517d3f': {
    name: 'AccessControlUnauthorizedAccount',
    inputs: [
      { name: 'account', type: 'address' },
      { name: 'neededRole', type: 'bytes32' },
    ],
    source: 'AUT_Roles_v2',
  },
  '0x0f2a11ba': {
    name: 'CallFailed',
    inputs: [{ name: 'call', type: 'tuple' }],
    source: 'TransactionForwarder_v1',
  },
  '0x4ca249dc': {
    name: 'Create2EmptyBytecode',
    inputs: [],
    source: 'DeterministicFactory_v1',
  },
  '0xc86af699': {
    name: 'DeterministicFactory__NotAllowed',
    inputs: [],
    source: 'DeterministicFactory_v1',
  },
  '0xe04b1819': {
    name: 'DiscreteCurveMathLib__InitialPriceTooLarge',
    inputs: [],
    source: 'Floor_v1',
  },
  '0xc9052a7a': {
    name: 'DiscreteCurveMathLib__InsufficientIssuanceToSell',
    inputs: [
      { name: 'requested_', type: 'uint256' },
      { name: 'available_', type: 'uint256' },
    ],
    source: 'Floor_v1',
  },
  '0x8765fe9e': {
    name: 'DiscreteCurveMathLib__InvalidFlatSegment',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x78878655': {
    name: 'DiscreteCurveMathLib__InvalidNumberOfSteps',
    inputs: [],
    source: 'Floor_v1',
  },
  '0xe80a3381': {
    name: 'DiscreteCurveMathLib__InvalidPointSegment',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x17cfecb6': {
    name: 'DiscreteCurveMathLib__InvalidPriceProgression',
    inputs: [
      { name: 'segmentIndex_', type: 'uint256' },
      { name: 'previousSegmentFinalPrice_', type: 'uint256' },
      { name: 'nextSegmentInitialPrice_', type: 'uint256' },
    ],
    source: 'Floor_v1',
  },
  '0x1e674ad4': {
    name: 'DiscreteCurveMathLib__NoSegmentsConfigured',
    inputs: [],
    source: 'Floor_v1',
  },
  '0xbca02987': {
    name: 'DiscreteCurveMathLib__PriceIncreaseTooLarge',
    inputs: [],
    source: 'Floor_v1',
  },
  '0xe4369ad8': {
    name: 'DiscreteCurveMathLib__SegmentIsFree',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x53888fca': {
    name: 'DiscreteCurveMathLib__SingleStepMustBeFlat',
    inputs: [{ name: 'segmentIndex_', type: 'uint256' }],
    source: 'Floor_v1',
  },
  '0xa1f6025c': {
    name: 'DiscreteCurveMathLib__SupplyExceedsCurveCapacity',
    inputs: [
      { name: 'providedSupply_', type: 'uint256' },
      { name: 'maxCapacity_', type: 'uint256' },
    ],
    source: 'Floor_v1',
  },
  '0x1f52d7ae': {
    name: 'DiscreteCurveMathLib__SupplyPerStepTooLarge',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x37f615e7': {
    name: 'DiscreteCurveMathLib__TooManySegments',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x73937fff': {
    name: 'DiscreteCurveMathLib__ZeroCollateralInput',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x406480c1': {
    name: 'DiscreteCurveMathLib__ZeroIssuanceInput',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x3c5094de': {
    name: 'DiscreteCurveMathLib__ZeroSupplyPerStep',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x9e79f854': {
    name: 'ERC20ExceededCap',
    inputs: [
      { name: 'increasedSupply', type: 'uint256' },
      { name: 'cap', type: 'uint256' },
    ],
    source: 'ERC20Issuance_v1',
  },
  '0xfb8f41b2': {
    name: 'ERC20InsufficientAllowance',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'allowance', type: 'uint256' },
      { name: 'needed', type: 'uint256' },
    ],
    source: 'ERC20Issuance_v1',
  },
  '0xe450d38c': {
    name: 'ERC20InsufficientBalance',
    inputs: [
      { name: 'sender', type: 'address' },
      { name: 'balance', type: 'uint256' },
      { name: 'needed', type: 'uint256' },
    ],
    source: 'ERC20Issuance_v1',
  },
  '0xe602df05': {
    name: 'ERC20InvalidApprover',
    inputs: [{ name: 'approver', type: 'address' }],
    source: 'ERC20Issuance_v1',
  },
  '0x392e1e27': {
    name: 'ERC20InvalidCap',
    inputs: [{ name: 'cap', type: 'uint256' }],
    source: 'ERC20Issuance_v1',
  },
  '0xec442f05': {
    name: 'ERC20InvalidReceiver',
    inputs: [{ name: 'receiver', type: 'address' }],
    source: 'ERC20Issuance_v1',
  },
  '0x96c6fd1e': {
    name: 'ERC20InvalidSender',
    inputs: [{ name: 'sender', type: 'address' }],
    source: 'ERC20Issuance_v1',
  },
  '0x94280d62': {
    name: 'ERC20InvalidSpender',
    inputs: [{ name: 'spender', type: 'address' }],
    source: 'ERC20Issuance_v1',
  },
  '0x94eef58a': {
    name: 'ERC2771ForwarderExpiredRequest',
    inputs: [{ name: 'deadline', type: 'uint48' }],
    source: 'TransactionForwarder_v1',
  },
  '0xc845a056': {
    name: 'ERC2771ForwarderInvalidSigner',
    inputs: [
      { name: 'signer', type: 'address' },
      { name: 'from', type: 'address' },
    ],
    source: 'TransactionForwarder_v1',
  },
  '0x70647f79': {
    name: 'ERC2771ForwarderMismatchedValue',
    inputs: [
      { name: 'requestedValue', type: 'uint256' },
      { name: 'msgValue', type: 'uint256' },
    ],
    source: 'TransactionForwarder_v1',
  },
  '0xd2650cd1': {
    name: 'ERC2771UntrustfulTarget',
    inputs: [
      { name: 'target', type: 'address' },
      { name: 'forwarder', type: 'address' },
    ],
    source: 'TransactionForwarder_v1',
  },
  '0xd6bda275': {
    name: 'FailedCall',
    inputs: [],
    source: 'TransactionForwarder_v1',
  },
  '0xb06ebf3d': {
    name: 'FailedDeployment',
    inputs: [],
    source: 'DeterministicFactory_v1',
  },
  '0xa4e0eec9': {
    name: 'FloorFactory__InvalidAddress',
    inputs: [],
    source: 'FloorFactory_v1',
  },
  '0x2e23a773': {
    name: 'FloorFactory__InvalidId',
    inputs: [],
    source: 'FloorFactory_v1',
  },
  '0x8333c4a6': {
    name: 'IERC20Issuance__CallerIsNotMinter',
    inputs: [],
    source: 'ERC20Issuance_v1',
  },
  '0xcf479181': {
    name: 'InsufficientBalance',
    inputs: [
      { name: 'balance', type: 'uint256' },
      { name: 'needed', type: 'uint256' },
    ],
    source: 'DeterministicFactory_v1, TransactionForwarder_v1',
  },
  '0x752d88c0': {
    name: 'InvalidAccountNonce',
    inputs: [
      { name: 'account', type: 'address' },
      { name: 'currentNonce', type: 'uint256' },
    ],
    source: 'TransactionForwarder_v1',
  },
  '0xf92ee8a9': {
    name: 'InvalidInitialization',
    inputs: [],
    source:
      'AUT_Roles_v2, CreditFacility_v1, FloorFactory_v1, Floor_v1, ModuleFactory_v1, Presale_v1, SplitterTreasury_v1, TransactionForwarder_v1',
  },
  '0xa972f3d2': {
    name: 'InverterBeacon__InvalidImplementation',
    inputs: [],
    source: 'InverterBeacon_v1',
  },
  '0x7c519051': {
    name: 'InverterBeacon__InvalidImplementationMinorOrPatchVersion',
    inputs: [],
    source: 'InverterBeacon_v1',
  },
  '0xbe27c5b7': {
    name: 'InverterReverter__ContractPaused',
    inputs: [],
    source: 'InverterReverter_v1',
  },
  '0x7e5cf732': {
    name: 'Module__Authorizer__CannotModifyAdminRoleAccess',
    inputs: [],
    source: 'AUT_Roles_v2',
  },
  '0x5b784de5': {
    name: 'Module__Authorizer__InvalidInitialAdmin',
    inputs: [],
    source: 'AUT_Roles_v2',
  },
  '0x7a625bbe': {
    name: 'Module__Authorizer__InvalidInputLength',
    inputs: [],
    source: 'AUT_Roles_v2',
  },
  '0xe1242708': {
    name: 'Module__Authorizer__RoleIdNotExisting',
    inputs: [],
    source: 'AUT_Roles_v2',
  },
  '0x1bb5195f': {
    name: 'Module__BC_Discrete_Redeeming_VirtualSupply__InvarianceCheckFailed',
    inputs: [
      { name: 'newCalculatedReserve_', type: 'uint256' },
      { name: 'currentVirtualCollateralSupply_', type: 'uint256' },
    ],
    source: 'Floor_v1',
  },
  '0x7ea9d542': {
    name: 'Module__CallerNotPermissioned',
    inputs: [],
    source: 'AUT_Roles_v2, CreditFacility_v1, Floor_v1, Presale_v1, SplitterTreasury_v1',
  },
  '0xb5d3d39c': {
    name: 'Module__CreditFacility_BorrowAmountTooSmall',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0x9860564d': {
    name: 'Module__CreditFacility_InsufficientCollateralForLeverage',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0xb8d4508f': {
    name: 'Module__CreditFacility_InsufficientIssuanceTokensReceived',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0xe5b90295': {
    name: 'Module__CreditFacility_InsufficientLoansToConsolidate',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0x5a123629': {
    name: 'Module__CreditFacility_InvalidBorrowAmount',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0xae6544c7': {
    name: 'Module__CreditFacility_InvalidFeeCalculatorAddress',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0xa4716b72': {
    name: 'Module__CreditFacility_InvalidFeeRate',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0x882a2be3': {
    name: 'Module__CreditFacility_InvalidLeverage',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0xecbc7909': {
    name: 'Module__CreditFacility_InvalidLoanId',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0xe8e3a91b': {
    name: 'Module__CreditFacility_InvalidLoansForConsolidation',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0x3f3c72cc': {
    name: 'Module__CreditFacility_InvalidReceiver',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0x85591c03': {
    name: 'Module__CreditFacility_InvalidTokenReceiver',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0xb1e5d973': {
    name: 'Module__CreditFacility_InvalidTransferRecipient',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0x26831539': {
    name: 'Module__CreditFacility_LoanToValueRatioTooHigh',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0xff17a9c5': {
    name: 'Module__CreditFacility_NoCollateralAvailable',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0x308e1d3b': {
    name: 'Module__CreditFacility_NoIssuanceTokensReceived',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0x0db6a82c': {
    name: 'Module__CreditFacility_NoLoansToConsolidate',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0xf3d0ae0e': {
    name: 'Module__CreditFacility_NoSegmentsConfigured',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0xea969350': {
    name: 'Module__CreditFacility_NothingToRebalance',
    inputs: [],
    source: 'CreditFacility_v1',
  },
  '0x54fe6890': {
    name: 'Module__Floor__InsufficientPremiumSteps',
    inputs: [],
    source: 'Floor_v1',
  },
  '0xd08bdb84': {
    name: 'Module__Floor__InsufficientSegments',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x62bcaf22': {
    name: 'Module__Floor__InvalidFloorSegment',
    inputs: [
      { name: 'numberOfSteps_', type: 'uint256' },
      { name: 'priceIncrease_', type: 'uint256' },
    ],
    source: 'Floor_v1',
  },
  '0x23c42ef0': {
    name: 'Module__Floor__NoFloorIncrease',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x51cfef5f': {
    name: 'Module__InvalidAddress',
    inputs: [],
    source: 'AUT_Roles_v2, CreditFacility_v1, Floor_v1, Presale_v1, SplitterTreasury_v1',
  },
  '0xde504dfe': {
    name: 'Module__InvalidAmount',
    inputs: [],
    source: 'AUT_Roles_v2, CreditFacility_v1, Floor_v1, Presale_v1, SplitterTreasury_v1',
  },
  '0xea7ec715': {
    name: 'Module__InvalidArrayLength',
    inputs: [],
    source: 'AUT_Roles_v2, CreditFacility_v1, Floor_v1, Presale_v1, SplitterTreasury_v1',
  },
  '0x85a2648b': {
    name: 'Module__IssuanceBase__BuyingFunctionaltiesClosed',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x21af7e45': {
    name: 'Module__IssuanceBase__InsufficientOutputAmount',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x99bb7d2d': {
    name: 'Module__IssuanceBase__InvalidDepositAmount',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x5489340e': {
    name: 'Module__IssuanceBase__InvalidFeePercentage',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x94ba0164': {
    name: 'Module__IssuanceBase__InvalidMinAmountOut',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x0a1cfefe': {
    name: 'Module__IssuanceBase__InvalidRecipient',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x484caa15': {
    name: 'Module__IssuanceBase__TradeAmountTooLow',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x9d4878c9': {
    name: 'Module__RedeemingIssuanceBase__InsufficientCollateralForProjectFee',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x9a71ec39': {
    name: 'Module__RedeemingIssuanceBase__SellingFunctionaltiesClosed',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x00f94c58': {
    name: 'Module__SplitterTreasury__FloorFeeTreasuryIsZeroAddress',
    inputs: [],
    source: 'SplitterTreasury_v1',
  },
  '0x14ecb929': {
    name: 'Module__SplitterTreasury__InvalidArrayLength',
    inputs: [],
    source: 'SplitterTreasury_v1',
  },
  '0xe1ddeaf8': {
    name: 'Module__SplitterTreasury__InvalidFeePercentage',
    inputs: [],
    source: 'SplitterTreasury_v1',
  },
  '0x7ba48bfd': {
    name: 'Module__SplitterTreasury__RecipientAlreadyExists',
    inputs: [],
    source: 'SplitterTreasury_v1',
  },
  '0x2c893c25': {
    name: 'Module__SplitterTreasury__RecipientIsZeroAddress',
    inputs: [],
    source: 'SplitterTreasury_v1',
  },
  '0xf4b9de6c': {
    name: 'Module__SplitterTreasury__SharesAreZero',
    inputs: [],
    source: 'SplitterTreasury_v1',
  },
  '0xae34fee4': {
    name: 'Module__VirtualCollateralSupplyBase__AddResultsInOverflow',
    inputs: [],
    source: 'Floor_v1',
  },
  '0xba7b44d6': {
    name: 'Module__VirtualCollateralSupplyBase__SubtractResultsInUnderflow',
    inputs: [],
    source: 'Floor_v1',
  },
  '0x5f60529f': {
    name: 'Module__VirtualCollateralSupplyBase__VirtualSupplyCannotBeZero',
    inputs: [],
    source: 'Floor_v1',
  },
  '0xb8ac5f88': {
    name: 'ModuleFactory__InvalidInitialRegistrationData',
    inputs: [],
    source: 'ModuleFactory_v1',
  },
  '0xf9596d32': {
    name: 'ModuleFactory__InvalidInverterBeacon',
    inputs: [],
    source: 'ModuleFactory_v1',
  },
  '0xadc1baa1': {
    name: 'ModuleFactory__InvalidMetadata',
    inputs: [],
    source: 'ModuleFactory_v1',
  },
  '0x9bc9dc56': {
    name: 'ModuleFactory__MetadataAlreadyRegistered',
    inputs: [],
    source: 'ModuleFactory_v1',
  },
  '0x79b3d744': {
    name: 'ModuleFactory__ModuleIsSunset',
    inputs: [],
    source: 'ModuleFactory_v1',
  },
  '0xbc885f3d': {
    name: 'ModuleFactory__UnregisteredMetadata',
    inputs: [],
    source: 'ModuleFactory_v1',
  },
  '0xd7e6bcf8': {
    name: 'NotInitializing',
    inputs: [],
    source:
      'AUT_Roles_v2, CreditFacility_v1, FloorFactory_v1, Floor_v1, ModuleFactory_v1, Presale_v1, SplitterTreasury_v1, TransactionForwarder_v1',
  },
  '0x1e4fbdf7': {
    name: 'OwnableInvalidOwner',
    inputs: [{ name: 'owner', type: 'address' }],
    source:
      'DeterministicFactory_v1, ERC20Issuance_v1, FloorFactory_v1, InverterBeacon_v1, ModuleFactory_v1',
  },
  '0x118cdaa7': {
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address' }],
    source:
      'DeterministicFactory_v1, ERC20Issuance_v1, FloorFactory_v1, InverterBeacon_v1, ModuleFactory_v1',
  },
  '0x842b8bd1': {
    name: 'Presale__AfterEndTimestamp',
    inputs: [],
    source: 'Presale_v1',
  },
  '0xdb351373': {
    name: 'Presale__GlobalCapExceeded',
    inputs: [],
    source: 'Presale_v1',
  },
  '0xd6ec36a7': {
    name: 'Presale__InvalidBps',
    inputs: [{ name: 'bps_', type: 'uint256' }],
    source: 'Presale_v1',
  },
  '0x5cd7b824': {
    name: 'Presale__InvalidEndTimestamp',
    inputs: [],
    source: 'Presale_v1',
  },
  '0x29168c21': {
    name: 'Presale__InvalidLeverageIndex',
    inputs: [{ name: 'leverageIndex_', type: 'uint256' }],
    source: 'Presale_v1',
  },
  '0xfab2a8f9': {
    name: 'Presale__InvalidPosition',
    inputs: [{ name: 'positionId_', type: 'uint256' }],
    source: 'Presale_v1',
  },
  '0xbd5fc4da': {
    name: 'Presale__InvalidTranche',
    inputs: [
      { name: 'positionId_', type: 'uint256' },
      { name: 'trancheIndex_', type: 'uint256' },
    ],
    source: 'Presale_v1',
  },
  '0x189bb1f2': {
    name: 'Presale__NotEnded',
    inputs: [],
    source: 'Presale_v1',
  },
  '0x8c66b6e0': {
    name: 'Presale__NotOpen',
    inputs: [],
    source: 'Presale_v1',
  },
  '0x654a5dde': {
    name: 'Presale__NotStarted',
    inputs: [],
    source: 'Presale_v1',
  },
  '0x63a69154': {
    name: 'Presale__NotWhitelisted',
    inputs: [],
    source: 'Presale_v1',
  },
  '0xc19cf6bb': {
    name: 'Presale__PerAddressCapExceeded',
    inputs: [],
    source: 'Presale_v1',
  },
  '0x62df6dff': {
    name: 'Presale__TrancheNotClaimable',
    inputs: [
      { name: 'positionId_', type: 'uint256' },
      { name: 'trancheIndex_', type: 'uint256' },
    ],
    source: 'Presale_v1',
  },
  '0x3ee5aeb5': {
    name: 'ReentrancyGuardReentrantCall',
    inputs: [],
    source: 'Presale_v1',
  },
  '0x5274afe7': {
    name: 'SafeERC20FailedOperation',
    inputs: [{ name: 'token', type: 'address' }],
    source: 'CreditFacility_v1, Floor_v1, Presale_v1, SplitterTreasury_v1',
  },
} as const

// ============================================================================
// Utility Types
// ============================================================================

/**
 * Type guard to check if a signature is a known error.
 */
export function isKnownErrorSignature(signature: string): signature is KnownErrorSignature {
  return signature in ERROR_METADATA
}

/**
 * Get error metadata by signature.
 */
export function getErrorMetadata(signature: KnownErrorSignature): ErrorMetadata {
  return ERROR_METADATA[signature]
}

/**
 * Get all known error signatures.
 */
export function getAllErrorSignatures(): KnownErrorSignature[] {
  return Object.keys(ERROR_METADATA) as KnownErrorSignature[]
}

/**
 * Find error signature by name (case-insensitive partial match).
 */
export function findErrorByName(name: string): KnownErrorSignature | null {
  const lowerName = name.toLowerCase()
  for (const [sig, meta] of Object.entries(ERROR_METADATA)) {
    if (meta.name.toLowerCase().includes(lowerName)) {
      return sig as KnownErrorSignature
    }
  }
  return null
}
